import React from "react";
import Head from "next/head";
//import Link from "next/link"; //Esto es una libreria para que sustituyamos los a href por Link y asi nuestra pagina es una SPA (single Page App)
import AppLayout from "@/components/AppLayout";
import { colors } from "@/styles/theme";
import Button from "@/components/Button";
import GitHub from "@/components/Icons/GitHub";
import { loginWithGitHub, onAuthStateChanged } from "../firebase/client";
import { useEffect, useState } from "react";
import Avatar from "@/components/Avatar";
import Logo from "@/components/Icons/Logo";

export default function Home() {
  const [user, setUser] = useState(undefined);

  useEffect(() => {
    onAuthStateChanged(setUser);
  }, []);

  const handleClick = () => {
    loginWithGitHub()
      .then((user) => {
        const { avatar, username } = user;
        setUser(user);
      })
      .catch((err) => {
        console.log(err);
      });
  };
  return (
    <>
      <Head>
        <title>Devter 🦜</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <Logo width="100" />
          <h1>Devter</h1>
          <h2>Talk about development with developers</h2>

          <div>
            {user === null && (
              <Button onClick={handleClick}>
                <GitHub fill="white" width={24} height={24} />
                Login with Github
              </Button>
            )}
            {user && user.avatar && (
              <div>
                <Avatar
                  alt={user.username}
                  src={user.avatar}
                  text={user.username}
                />
              </div>
            )}
          </div>
        </section>
      </AppLayout>

      <style jsx>{`
        img {
          width: 120px;
        }

        div {
          margin-top: 16px;
        }

        h1 {
          color: ${colors.primary};
          font-weight: 800;
          font-size: 32px;
          margin-bottom: 16px;
        }

        h2 {
          color: ${colors.secondary};
          font-size: 21px;
          margin: 0;
        }

        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }
      `}</style>
    </>
  );
}
