import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from 'next/link' //Esto es una libreria para que sustituyamos los a href por Link y asi nuestra pagina es una SPA (single Page App) 
import AppLayout from "@/components/AppLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tuiter 🦜</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <h1>
          <a href="https://nextjs.org">Tuiter</a>
        </h1>
        </AppLayout>
    </>
  );
}
